MolecularMatters/raw_pdb

src/Foundation/PDB_BitUtil.h
src/Foundation/PDB_Macros.h
src/Foundation/PDB_PointerUtil.h
src/PDB_CoalescedMSFStream.cpp
src/PDB_CoalescedMSFStream.h
src/PDB_DBITypes.h
src/PDB_GlobalSymbolStream.h
src/PDB_PublicSymbolStream.h
src/PDB_Types.h

As discussed, this compiles under VS2015, 2017, 2019, and 2022 as C++11, though there is a link error related to the usage of `_BitScanForward` under 2015 and 2017.
- Removed nested namespaces
- PDB_NO_DISCARD is now only defined if the compiler & std level supports it
- Replaced usages of std::byte with std::uint8_t
- Removed inline from static const variables

Fixes for compilation under C++11

---

src/Examples/ExampleTypes.cpp

strnlen() is in <cstring>, POSIX.1-2008
/tmp/raw_pdb/src/Examples/ExampleTypes.cpp:681:22: error: ‘strnlen’ was not declared in this scope
681 |                 i += strnlen(leafName, maximumSize - i - 1) + 1;
|                      ^~~~~~~

fix build on Linux

---

src/Foundation/PDB_BitUtil.h

Fixes compile error when building with Mingw-w64
Reference: https://docs.microsoft.com/en-us/cpp/intrinsics/bitscanforward-bitscanforward64

#include <intrin.h> on Windows.

---

src/Examples/ExampleFunctionSymbols.cpp
src/Examples/ExampleMain.cpp
src/Examples/ExampleTypes.cpp

1. Fix null pointer deference which result in a crash.
2. Fix compiler warnings in VS2022.
3. Make "Incorrect usage" error actionable.

Examples fixes

---

src/Foundation/PDB_Macros.h
src/PDB_CoalescedMSFStream.cpp
src/PDB_DBIStream.cpp
src/PDB_DirectMSFStream.cpp
src/PDB_DirectMSFStream.h

- Fixed compile issue (incorrect preprocessor test in PDB_Macros.h)
- Fixed crash in `DBIStream::HasValidImageSectionStream`: the `DebugHeaderSubstream` is optional. If it's missing, `HasValidImageSectionStream` would crash because it would try to read past the end of the buffer.
- Fixed crash when iterating through modules in the `ModuleInfoStream`, caused by garbage data in the Modules list. The root cause was an issue in `CoalescedMSFStream`: the `AreBlockIndicesContiguous` test could incorrectly return true when reading <= `blockSize` bytes from a non-zero `offset` in the block. This would result in a read that *should* have been reading from multiple disjoint blocks to instead read past the end of the block that the `offset` was in, resulting in `offset` bytes of garbage data being …

Compile & crash fixes

---

src/Examples/ExampleSymbols.cpp
src/PDB_DBITypes.h

Used to reference stack variables since they're stored relatively to the RSP register.

Add S_REGREL32, register relatively stored symbol

---

src/Examples/ExampleTypes.cpp

The modifier record checked the volatile attribute twice in succession.

Resolve typo in GetModifierName

---

src/Examples/ExampleLines.cpp

Adding `#include <cstring>` to `src/Examples/ExampleLines.cpp`. Fixes issue #43.

Include 'cstring' header

---

src/Examples/ExampleLines.cpp

Each Line has a filenameIndex instead of containing the filename related fields.
Makes the overall PDB lines structure clearer and makes "Storing lines from modules " 1.3x faster
Before
====
Running example "Lines"
| Reading image section stream
| ---> done in 0.049ms
| Reading module info stream
| ---> done in 0.208ms
| Reading names stream
| ---> done in 6.324ms
| Storing lines from modules
| ---> done in 227.087ms (1815 elements)
| std::sort sections
| ---> done in 87.234ms (3895467 elements)
After 
===
Running example "Lines"
| Reading image section stream
| ---> done in 0.043ms
| Reading module info stream
| ---> done in 0.172ms
| Reading names stream
| ---> done in 5.428ms
| Storing lines from modules
| ---> done in 167.206ms (1815 elements)
| std::sort sections
| ---> done in …

Improve ExampeLines example

---

build/Examples.vcxproj
build/Examples.vcxproj.filters
src/Examples/CMakeLists.txt
src/Examples/ExampleFunctionVariables.cpp
src/Examples/ExampleMain.cpp
src/Examples/ExampleTypes.cpp
src/PDB_DBITypes.h

* Added an example of how to print function variables and added the necessary DBI records.
* Some improvements and extensions ExampleTypes, which the function variables example utilized.
Tested with various clang and Unreal Engine 5 PDBs, up to 1.45 GiB in size.
928 MiB clang 13 debug PDB built with VS 2022 along with output from function variables example can be downloaded from here:
http://lukekasz.com/raw_pdb/raw-pdb-function-variables.zip (223 MiB)
**Snippet of example output from clang main function**
```
S_GPROC32 Function 'main' | RVA 0x4D440
S_FRAMEPROC: Size 7704 | Padding 0 | Padding Offset 0x0 | Callee Registers Size 16
S_FRAMECOOKIE: Offset 0x1E08 | Register 335 | Type 1
S_REGREL32: 'Argc' -> 'INT' | Register 335 | Register Offset 0x1E30
S_REGREL32: 'Argv' -> 'CHAR' | Register …
```

Function variables support and example

---

src/CMakeLists.txt

This pr adds the possibility to install library to a standard directory under Linux.
Users don't need to manage the installation of the library itself anymore given they are under a Linux OS.

Add possibility to install library to a standard directory under Linux

---

src/PDB_ModuleLineStream.h

The section size already includes the size of InlineeSourceLineHeader, but when processing section S_INLINEELINES both were added to the offset. This caused headerEnd to be beyond the end of the section, resulting in an out of bounds read and corrupt data. 
When processing normal lines (section S_LINES), headerEnd is calculated correctly.

Fixed out of bounds read when looping over InlineeSourceLines

---

src/Examples/ExampleFunctionVariables.cpp
src/Examples/ExampleTypes.cpp
src/PDB_DBITypes.h

Fix issue with LF_MFUNCTION not being handled correctly in LF_PROCEDURE and LF_MFUNCTION arglist. This happens when a function or class method has a class method pointer as a parameter.
Fixes https://github.com/MolecularMatters/raw_pdb/issues/60
Also added S_REGREL32_INDIR (0x1171) record kind, which I encountered while testing on the 3.65 GB Qt6WebEngineCored.pdb
Both Qt6WebEngineCore.pdb and Qt6WebEngineCored.pdb used for testing can be downloaded from here: 
http://lukekasz.com/raw_pdb/Qt6WebEngineCore-pdbs.zip

Arglist LF_MFUNCTION fix and S_REGREL32_INDIR (0x1171)

---

src/Examples/ExampleFunctionVariables.cpp
src/Examples/ExampleTypes.cpp
src/PDB_DBITypes.h

Should be merged after https://github.com/MolecularMatters/raw_pdb/pull/62, as the changes in that PR have also been merged into this branch, to avoid a conflict.
Source code compiled with VS 2022
```
namespace
{
class base
{
};
class derived1 : virtual public base
{		
};
}
int main()
{
derived1 temp;
return 0;
}
```
ExamplesFunctionVariables output:
```
S_LPROC32 Function '`anonymous namespace'::derived1::derived1' | RVA 0x11780
S_FRAMEPROC: Size 200 | Padding 192 | Padding Offset 0x0 | Callee Registers Size 16
S_REGREL32: 'this' -> '`anonymous-namespace'::derived1' | Register 334 | Register Offset 0xE0
S_REGREL32_ENCTMP: '$initVBases' -> 'UINT' | Register 334 | Register Offset 0xE8
S_END
```
Fixes https://github.com/MolecularMatters/raw_pdb/issues/58
Test PDB: …

Add support for record kind S_REGREL32_ENCTMP (0x1179)

---

src/Examples/ExampleFunctionVariables.cpp
src/Examples/ExampleLines.cpp
src/Examples/ExampleTypes.cpp
src/PDB_DBITypes.h
src/PDB_TPITypes.h

Fixes issue https://github.com/MolecularMatters/raw_pdb/issues/32 and https://github.com/MolecularMatters/raw_pdb/issues/59
In the chrome.dll.pdb there is a type with type index 0x0600, which looks like a compiler bug to me.
I believe I correctly tracked down the code for one of the places it was used. 
Output from function variables example:
```
S_LOCAL: 'PUINT' -> 'in_count'
S_CONSTANT: 'UNKNOWN_0x0600' -> 'ªªªªªªªªcount' | Value 0x8009
S_CONSTANT: 'UINT' -> 'ªªªªexpected' | Value 0x8003
S_CONSTANT: 'UINT' -> 'ªªªªnew_value' | Value 0x8003
```
Code:
```C
// Type definition
typedef _Atomic uint32_t CRYPTO_atomic_u32;
// Function
void CRYPTO_refcount_inc(CRYPTO_refcount_t *in_count) {
CRYPTO_atomic_u32 *count = (CRYPTO_atomic_u32 *)in_count;
uint32_t expected = …
```

Chrome dll pdb fixes

---

src/Examples/ExampleTypes.cpp

Just a small fix to one of the examples. I noticed that the existing code can end up printing out invalid data. I unfortunately cannot share the PDB that is causing this but the issue is resolved by considering the kind of the field record.

Update DisplayEnumerates in ExampleTypes.cpp to take kind into account

---

src/CMakeLists.txt
src/Examples/Examples_PCH.h

Hi, first of all thank you for this brilliant library, I was able to parse pdb in a matter of minutes on linux, the api is self explanatory and the examples are helpful.
There is currently no way to skip building the examples.
I saw in https://github.com/MolecularMatters/raw_pdb/pull/48#issuecomment-1634166028 that the examples should always be built, but having to constantly rebuild the examples is time consuming, hence why having an option to skip them which is **off by default**, would be nice.
I also fixed a build error in `ExampleFunctionVariables.cpp`
```
src/Examples/ExampleFunctionVariables.cpp:33:9: error: ‘va_start’ was not declared in this scope
33 |         va_start(args, format);
|         ^~~~~~~~
src/Examples/ExampleFunctionVariables.cpp:38:9: error: ‘va_end’ was not …
```

Add option to toggle building the examples

---

src/Examples/ExampleMain.cpp
src/Examples/ExampleTypes.cpp
src/Foundation/PDB_ArrayView.h
src/PDB_TPITypes.h

This PR contains three small fixes and a new example. I have been working with large PDBs and needed to understand what makes up the TPI stream, which is what the example is about. Yes, I know it would be great to split this into three PRs, but my days are long and my freetime is short :)
Fixes:
- Add missing include in PDB_ArrayView. Self-explanatory. Not sure why it broke since the project should be using PCHs anyway, but I have observed this failure a few times locally.
-  Correct broken `LF_INDEX` type. The `LF_INDEX` type has a `uint16_t leaf` member as its first member according to Microsoft, but that's actually something that _all_ of the structs that are within the `FieldList` struct have. So RawPDB made the sensible choice of moving it out of the inner struct into the outer …

TPI size example

---

src/Examples/ExampleTypes.cpp

/raw_pdb/src/Examples/ExampleTypes.cpp:1397:32: warning: format not a string literal and no format arguments [-Wformat-security]
1397 |                         fprintf(f, kindName);

ExampleTypes: fix no format args

---

src/Examples/ExamplePDBSize.cpp

raw_pdb/src/Examples/ExamplePDBSize.cpp:87:42: warning: use of ‘h’ length modifier with ‘s’ type character has either no effect or undefined behavior [-Wformat=]
87 |                         printf("Module %hs (%hs) stream size: %u KiB (%u MiB)\n", name, objectName, moduleStreamSize >> 10u, moduleStreamSize >> 20u);

ExamplePDBSize: fix %hs format string

---

src/Examples/ExampleFunctionVariables.cpp
src/Examples/ExampleTypes.cpp
src/PDB_DBITypes.h

Fixed handling of some large private PDB files, including PDBs for x86-32 and ARM64.
Note there's still one assert left in ExampleLines for S_CROSSSCOPEEXPORTS/S_CROSSSCOPEIMPORTS for these PDBs, but at least this one doesn't affect much and is skipped in the release build.
Test PDBs were produced by Microsoft and can be downloaded here: https://pastebin.com/W9MaCmq0 (password: "infected"). Set includes some binaries for easier testing.

Privatepdb fix

---

raw_pdb.natvis
src/Examples/ExampleMain.cpp
src/Examples/ExampleMemoryMappedFile.cpp
src/Examples/ExampleMemoryMappedFile.h
src/PDB.cpp
src/PDB.h
src/PDB_ErrorCodes.h
src/PDB_InfoStream.cpp

Hello, Folks!
I'm trying to use the `raw_pdb` library for parsing PDB files and have found several issues that I believe are worth fixing:
- I was concerned that during validation, the library didn't consider the actual size of the data. Therefore, I added an ability to check the data size during file validation.
- I found a minor bug: `InfoStream` constructor didn't initialize `m_namesStreamIndex`. As a result, when the PDB doesn't have a `"/names"` stream, it leads to garbage in `m_namesStreamIndex`, causing the method `InfoStream::HasNamesStream` to not work properly.
- I added a simple `Natvis` file for an array to make debugging easier. I think I could extend it further later on.
Please take a look.
Thanks!

Check the PDB data size & Initialize name stream

---

src/Examples/ExampleFunctionVariables.cpp
src/PDB_DBITypes.h

Hello! This patch adds support for `S_UNAMESPACE`. 
https://github.com/microsoft/microsoft-pdb/blob/805655a28bd8198004be2ac27e6e0290121a5e89/include/cvinfo.h#L2894
https://github.com/microsoft/microsoft-pdb/blob/805655a28bd8198004be2ac27e6e0290121a5e89/include/cvinfo.h#L4142
Please take a look.

Support S_UNAMESPACE

---

src/Examples/ExampleTypes.cpp

This commit makes `ExampleTypes.cpp` consistent with C++11 standard required in `CMakeLists.txt`.

Make ExampleTypes.cpp c++11 compatible

---

src/Examples/ExampleMain.cpp

The examples erroneously create a TPI stream before checking that it is valid to do so. This is likely a copy-paste error, as on a first look it seems that we are doing the same for DBI. However, for DBI there are _two_ checks, which has probably created this confusion:

Check TPI stream is valid before creating it

---

src/Examples/ExampleMain.cpp
src/PDB_IPIStream.cpp
src/PDB_InfoStream.cpp
src/PDB_InfoStream.h

PDBs created with older toolchains may not have an IPI stream. The stream's presence is advertised in the PDB-stream itself: at the end of the stream, there is a list of "feature codes". If the `VC110` or `VC140` feature code is present, then the PDB has an IPI stream. Otherwise it doesn't.
This PR adds detection for this scenario. I don't have strong feelings for whether the `HasValidIPIStream` should return `ErrorCode::InvalidStream` or something else.

Check for IPI Stream
